image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging
  - deploy

deploy_to_heroku:
  stage: staging
  only:
    - master
  script:
    - dpl --provider=heroku --app=${HEROKU_APP_NAME} --api-key=${HEROKU_APP_KEY}

update_docker_image:
  stage: deploy
  only:
    - master
  script:
    - docker login ${CI_REGISTER} -u ${CI_REGISTER_USERNAME} -p ${CI_REGISTER_PASSWORD}
    - docker build -t ${CI_REGISTER}/p9084/backend .
    - docker push ${CI_REGISTER}/p9084/backend